### ISSUE TITLE
"No mode matched, Missing class samba::classic or samba::dc?" on previously working samba::share

### ISSUE THREAD

**Issue by ariacomputer** [kakwa/puppet-samba#25] opened 2016-08-21 15:28 UTC
As of the latest version (possibly earlier, I haven't upgraded in a bit) my samba::share definitions are throwing this error:

**Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, No mode matched, Missing class samba::classic or samba::dc? at /etc/puppetlabs/code/environments/production/modules/samba/manifests/share.pp:61:4 at /etc/puppetlabs/code/environments/production/manifests/site.pp:262 on node sambashares.example.com"**

samba::classic is initialized in a previous module:

```
  class {'::samba::params':
    sernetpkgs => true,
  }
  class {'::samba::classic':
    smbname => $hostname,
    domain => 'EXAMPLE',
    realm => 'EXAMPLE.COM',
    security => 'ads',
    krbconf => true,
    nsswitch => true,
    globaloptions => {
      'workgroup' => 'EXAMPLE',
      'template shell' => '/bin/bash',
    },
    adminuser => 'Administrator',
    adminpassword => 'PASSWORD',
  }
  ::samba::idmap { 'Domain *':
    domain => '*',
    idrangemin => 16777216,
    idrangemax => 33554431,
    backend => 'tdb',
    schema_mode => 'rfc2307',
  }
```

and samba::share is initialized in the main manifest.

```
  ::samba::share {'RAID':
    path => '/raid/',
    owner => 'root',
    group => 'root',
    mode => '0775',
    options => {
        'browsable' => 'yes',
        'read only' => 'no',
        'public' => 'yes',
        'writable' => 'yes',
        'valid users' => 'admin',
    },
  }
```

Am I just doing something stupid?

**Comment by ariacomputer** [comment] 2016-08-21 15:38
If I comment out some of the checks in share.pp and force it to use SambaClassic and SambaWinbind as the require and notify, respectively, it works:

```
  #if defined(Package['SambaClassic']){
    $require = Package['SambaClassic']
  #  if defined(Service['SambaWinbind']) {
      $notify  = Service['SambaSmb', 'SambaWinBind']
  #  }
  #  else {
  #    $notify  = Service['SambaSmb']
  #  }
  #}elsif defined(Package['SambaDC']){
  #  $require = Exec['provisionAD']
  #  $notify  = Service['SambaDC']
  #}else{
  #  fail('No mode matched, Missing class samba::classic or samba::dc?')
  #}
```

[share.pp.diff.txt](https://github.com/kakwa/puppet-samba/files/428923/share.pp.diff.txt)

There appears to be some issue with how it's detecting if the package exists already; my best guess is that doing it across modules is causing an issue, but I'm not sure.

**Comment by kakwa** [comment] 2016-08-21 15:46
This part was changed in the last pull request: https://github.com/kakwa/puppet-samba/pull/24/files

However, it's a little strange, I don't see how it may result in this error...

I will take a look this week.

By the way, which version of puppet do you use?

**Comment by ariacomputer** [comment] 2016-08-21 16:06
Tested it on v3.8.7 and v4.6.0 with the same error.  I'm guessing it's a scope issue, but again, spitballing :)

**Comment by kirkmadera** [comment] 2016-10-14 01:45
Is this module intended to work with only users and shares defined? I don't understand how to set up classic or dc.

**Comment by kakwa** [comment] 2016-12-08 23:09
could not reproduce using:

```puppet
class stuff(
   $hostname = 'stuff'
){

  class {'::samba::params':
    sernetpkgs => false,
  }

  class {'::samba::classic':
    smbname => $hostname,
    domain => 'EXAMPLE',
    realm => 'EXAMPLE.COM',
    security => 'ads',
    krbconf => true,
    nsswitch => true,
    join_domain         => false,

    globaloptions => {
      'workgroup' => 'EXAMPLE',
      'template shell' => '/bin/bash',
    },
    adminuser => 'Administrator',
    adminpassword => 'PASSWORD',
  }
  ::samba::idmap { 'Domain *':
    domain => '*',
    idrangemin => 16777216,
    idrangemax => 33554431,
    backend => 'tdb',
    schema_mode => 'rfc2307',
  }
}
  ::samba::share {'RAID':
    path => '/raid/',
    owner => 'root',
    group => 'root',
    mode => '0775',
    options => {
        'browsable' => 'yes',
        'read only' => 'no',
        'public' => 'yes',
        'writable' => 'yes',
        'valid users' => 'admin',
    },
  }

class{ 'stuff':
  hostname => 'stuff.kakwa.fr',
}
```

closing for now

**Closed as completed by kakwa** 2016-12-08 23:09 UTC
