### ISSUE TITLE
syslog only is deprecated

### ISSUE THREAD

**Issue by iainhallam** [kakwa/puppet-samba#37] opened 2017-05-15 15:31 UTC
I'm getting warnings in my smbd logs that syslog only is deprecated. Looks like that will eventually get replaced by `logging` directives in the smb.conf.

**Comment by kakwa** [comment] 2017-05-15 16:06
hello, could you give me the version of samba you're using.

**Comment by kakwa** [comment] 2017-05-15 16:06
hello, could you give me the version of samba you're using.

**Comment by iainhallam** [comment] 2017-05-15 16:53
Samba 4.4.4 as installed by CentOS 7 system packages.

**Comment by jgbillings** [comment] 2017-05-17 01:02
Also getting that from Ubuntu 16.04 packaged version of Samba after a fresh setup using this module:  

```
root@cat-test-samba1:~# smbclient -L localhost -U%
WARNING: The "syslog only" option is deprecated
```

Samba package version is: 4.3.11+dfsg-0ubuntu0.16.04.3

**Comment by kakwa** [comment] 2017-05-24 18:02
Hello:

The issue is fixed by the 2 following commits:

Add custom facts to recover the samba version:
https://github.com/kakwa/puppet-samba/commit/12ea677714f61210db927755f042506039d09f24

Add syslog option handling per samba version:
https://github.com/kakwa/puppet-samba/commit/f61965e7087b7cd952963534103ba8816c2bf3b8

This will be included in next release.

**Closed as completed by kakwa** 2017-05-24 18:02 UTC
