### ISSUE TITLE
undefined method `permission' for Smb_acl

### ISSUE THREAD

**Issue by clauded** [kakwa/puppet-samba#17] opened 2015-12-03 20:31 UTC
When setting acl in samba classic I get:

Error: /Stage[main]/Site::Samba::Win_profiles/Samba::Share[profiles]/Samba::Dir[/srv/samba/profiles]/Smb_acl[/srv/samba/profiles]: Could not evaluate: undefined method `permission' for Smb_acl[/srv/samba/profiles](provider=genericacl):Puppet::Type::Smb_acl::ProviderGenericacl

This is my script:

``` ruby
  class { 'samba::classic':
    domain              => $domain,
    realm               => $realm,
    smbname             => $::hostname,
    security            => 'ADS',
    krbconf             => true,
    nsswitch            => true,
    adminuser           => $adminuser,
    adminpassword       => $adminpassword,
    logtosyslog         => true,
    sambaloglevel       => 0,
    globaloptions       => {
      'vfs objects'           => 'acl_xattr',
      'map acl inherit'       => 'yes',
      'store dos attributes'  => 'yes',
      'load printers'         => 'no',
      'printcap name'         => '/dev/null',
      'printing'              => 'bsd',
      'disable spoolss'       => 'yes',
    },
    globalabsentoptions => [ 
      'winbind separator',
    ],
    require             => Host["$::fqdn"],
  }
  package { 'acl':
    ensure => present,
    before => Samba::Share["$share1"],
  }
  samba::idmap { 'Domain *':
    domain      => '*',
    idrangemin  => 1000000,
    idrangemax  => 1999999,
    backend     => 'autorid',
    before      => Samba::Share["$share1"],
  }
  samba::share { "$share1":
    path    => "${mount_root}/${share1}",
    options => {
      'read only' => 'no',
    },
    mode    => 0770,
    acl     =>
      [
        'group::rwx',
        "group:${domain_admins}:rwx",
        "group:${domain_users}:r-x",
        'mask::rwx' ,
        'other::---',
        'user::rwx',
      ],
  }
```

**Comment by kakwa** [comment] 2016-12-07 21:52
Could not reproduce on Debian 8, closing.

**Closed as completed by kakwa** 2016-12-07 21:52 UTC
